version: '3.8'

services:
  ia-backend:
    container_name: ia-backend-experiments
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
    image: grafana/alloy:latest
    container_name: alloy-agent
    volumes:
      - ./grafana/config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    ports:
      - "12345:12345"
    restart: unless-stopped
    depends_on:
      ia-backend:
        condition: service_healthy
