{
 "title": "IA Backend Observability",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Estado del Servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"prometheus.scrape.springboot\"}",
     "legendFormat": "Estado"
    }
   ]
  },
  {
   "title": "Prompts Procesados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "openai_prompts_processed_total{model=\"gpt-3.5-turbo\"}",
     "legendFormat": "Processed Prompts"
    }
   ]
  },
  {
   "title": "Prompts Fallidos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "openai_prompts_failed_total", "legendFormat": " Prompts Fallidos" }
   ]
  },
  {
   "title": "Latencia OpenAPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "openai_latency_seconds", "legendFormat": "Latencia OpenAPI" }
   ]
  }
 ]
}